### ISSUE TITLE
Subaccount user name was used to allocate SWR location

### ISSUE THREAD

**Issue by paulmchen** [CPE-OAuth/servicestage-eclipse-plugin#27]
When user's account is a subaccount from an organization, the domain name is used to login to the subaccount. User would have to create an organization and a software repository in order to support SS deployment use cases via Eclipse plugins.

One of the issues is currently we are hardcoding the subaccount organization name as its user's subaccount username. This will introduce issue if user creates an organization with SWR that will not use the username as the name of the organization, the Eclipse plugins UI will not see the SWR repository created. 

A fix is to modify the existing Eclipse plugin UI and add an option that user can select an organization from the list , so the SWR calls will not hardcode "username" as the SWR organization name.

**Comment by farhan3** [comment]
[0001-add-swr-namespace-selection.zip](https://github.com/CPE-OAuth/servicestage-eclipse-plugin/files/3129375/0001-add-swr-namespace-selection.zip)
