### ISSUE TITLE
"platform_type" parameter is now a mandatory parameter for the ServiceStage provisioning request body.

### ISSUE THREAD

**Issue by paulmchen** [CPE-OAuth/servicestage-eclipse-plugin#6]
The following provisioning request body parameter has been changed to be a mandatory parameter in the service stage backend code. 
 "parameters": {
      "platform_type": "cce",
     ...
}

The eclipse plugin code didn't send this parameter when provisioning an application, this cause issues when running "configure k8s" steps in the jobflow. 

Adding "platform_type" as cce to the current plugins, since we only support CCE at this moment in the plugins, the value of "cce" can be hardcoded for now.

**Comment by paulmchen** [comment]
Hi Farhan, ServiceStage backend code had been changed to make request parameter parameters.platform_type to be mandatory, this broke our eclipse plugins, i made the changes in both eclipse java client and eclipse plugin projects to send platform_type as cce when running the provisioning. Please review my changes, i will merge it in so we can run a test against the new servicestage build. thanks!

**Comment by farhan3** [comment]
reviewed and verified
